import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {emptyState,applyCommand} from '../web/core/model.mjs';
import {startActivityTracking} from '../web/core/activity.mjs';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222';
const migration=new URL('../supabase/migrations/20260917055129_public_signup_analytics.sql',import.meta.url);
test('open signup preserves users; analytics is admin-only and daily activity is deduplicated',async()=>{
 const db=new PGlite();
 try{
  await db.exec(`create role anon;create role authenticated;create role supabase_auth_admin;create schema auth;
   create table auth.users(id uuid primary key,created_at timestamptz default now(),email_confirmed_at timestamptz,raw_user_meta_data jsonb);
   create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
   grant usage on schema auth,public to authenticated,anon,supabase_auth_admin;
   grant execute on function auth.uid() to authenticated,anon;
   grant select,insert,update on auth.users to supabase_auth_admin;
   insert into auth.users(id,email_confirmed_at) values('${A}',now());`);
  await db.exec(await readFile(new URL('../supabase/setup.sql',import.meta.url),'utf8'));
  await db.exec(await readFile(new URL('../supabase/invitations.sql',import.meta.url),'utf8'));
  await db.exec('set role supabase_auth_admin');
  await assert.rejects(db.query('insert into auth.users(id) values($1)',[B]),/Invitation/);
  await db.exec('reset role');
  await db.exec(await readFile(migration,'utf8'));
  await db.exec(await readFile(migration,'utf8')); // safe repeat without resetting coverage
  await db.exec(`insert into offer_private.admins values('${A}');set role supabase_auth_admin;`);
  await db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',[B,{admin:true,role:'admin'}]);
  await db.exec('reset role;set role anon');
  for(const query of ['select public.offer_analytics(30)','select public.offer_record_activity()','select * from offer_private.admins'])await assert.rejects(db.query(query),/permission denied/);
  await db.exec('reset role;set role authenticated');
  const login=id=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
  await login(B);
  assert.equal((await db.query('select public.offer_is_admin() as admin')).rows[0].admin,false);
  await assert.rejects(db.query('select public.offer_analytics(30)'),/Administrator/);
  await assert.rejects(db.query('select offer_private.analytics(30)'),/Administrator/);
  await assert.rejects(db.query('insert into offer_private.admins values($1)',[B]),/permission denied/);
  await assert.rejects(db.query('select * from offer_private.activity_daily'),/permission denied/);
  await db.query('select public.offer_record_activity()');await db.query('select public.offer_record_activity()');
  const next=applyCommand(emptyState(),{type:'upsert',kind:'applications',record:{company:'Fictional test',role:'Engineer'}});
  await db.query('select public.offer_save_workspace($1,$2)',[0,next]);
  await assert.rejects(db.query('select public.offer_save_workspace($1,$2)',[0,next]),/OFFER_CONFLICT/);
  await login(A);
  await db.query('select public.offer_record_activity()');
  const {rows:[{report}]}=await db.query('select public.offer_analytics(7) as report');
  assert.equal(report.daily.length,7);
  assert.equal(report.summary.registered,2);assert.equal(report.summary.confirmed,1);
  assert.equal(report.summary.active_today,2);assert.equal(report.summary.active_7,2);
  assert.equal(report.summary.populated,1);assert.equal(report.summary.applications,1);
  assert.equal(report.summary.period_saves,1);assert.equal(report.daily.at(-1).writers,1);
  assert.equal(JSON.stringify(report).includes('Fictional test'),false);
  assert.equal(JSON.stringify(report).includes(A),false);
  await assert.rejects(db.query('select public.offer_analytics(100000)'),/Invalid date range/);
  await login('');await assert.rejects(db.query('select public.offer_record_activity()'),/Sign in/);
  await assert.rejects(db.query('select public.offer_analytics(7)'),/Administrator/);
  await db.exec(`reset role;insert into offer_private.activity_daily(user_id,day,saves) values('${A}',(now() at time zone 'Asia/Shanghai')::date-1,3),('${B}',(now() at time zone 'Asia/Shanghai')::date-8,2);set role authenticated;`);
  await login(A);
  const report30=(await db.query('select public.offer_analytics(30) as r')).rows[0].r;
  assert.equal(report30.summary.active_7,2);assert.equal(report30.summary.active_30,2);
  assert.equal(report30.summary.period_saves,6);
  await db.exec(`reset role;delete from offer_private.admins where user_id='${A}';set role authenticated;`);
  await assert.rejects(db.query('select public.offer_analytics(7)'),/Administrator/);
 }finally{await db.close();}
});
test('activity tracking ignores hidden pages, retries failure, and does not count polling as activity',async()=>{
 let callback,listener,calls=0,removed=false;
 const env={document:{visibilityState:'hidden',addEventListener:(_,fn)=>listener=fn,removeEventListener:()=>removed=true},setInterval:fn=>(callback=fn,1),clearInterval:()=>{}};
 const stop=startActivityTracking({rpc:async()=>{calls++;return {error:calls===1?Error('offline'):null};}},env);
 await callback();assert.equal(calls,0);
 env.document.visibilityState='visible';await listener();assert.equal(calls,1);
 await callback();assert.equal(calls,2);
 await callback();await listener();assert.equal(calls,2);stop();assert.equal(removed,true);
});
