import test from 'node:test';import assert from 'node:assert/strict';import {emptyState,applyCommand,normalize,normalizeImport,previewImport,parseCSV,validDate,exportState} from '../web/core/model.mjs';import {openStore} from '../server/db.mjs';
const job={id:'a',company:'示例',role:'工程师',status:'筛选中',source:'原文状态'};
test('status update keeps fields; delete detaches references; undo restores them',()=>{let s=applyCommand(emptyState(),{type:'upsert',kind:'applications',record:job});s=applyCommand(s,{type:'upsert',kind:'events',record:{id:'e',title:'一面',date:'2026-09-08',job:'a'}});s=applyCommand(s,{type:'upsert',kind:'applications',record:{id:'a',status:'面试'}});assert.equal(s.applications[0].source,'原文状态');assert.equal(s.history.at(-1).beforeStatus,'筛选中');s=applyCommand(s,{type:'delete',kind:'applications',id:'a'});assert.equal(s.events[0].job,'');s=applyCommand(s,{type:'undo'});assert.equal(s.events[0].job,'a');assert.equal(s.applications[0].status,'面试')});
test('invalid dates and links rejected; old notes migrate; JD is preserved',()=>{assert.equal(validDate('2026-02-30'),false);assert.throws(()=>normalize('events',{title:'面试',date:'2026-02-30'}));assert.throws(()=>normalize('applications',{...job,link:'javascript:alert(1)'}));assert.equal(normalize('applications',{...job,evidence:'老备注'}).notes,'老备注');assert.equal(normalize('applications',{...job,jd:'负责嵌入式开发'}).jd,'负责嵌入式开发')});
test('import deduplicates and is idempotent, updates are opt-in',()=>{let s=applyCommand(emptyState(),{type:'upsert',kind:'applications',record:job});const data={applications:[{...job,id:'new',status:'面试'}]};assert.equal(previewImport(s,data)[0].action,'update');assert.equal(applyCommand(s,{type:'import',data}).applications[0].status,'筛选中');s=applyCommand(s,{type:'import',data,overwrite:true});assert.equal(s.applications.length,1);assert.equal(s.applications[0].status,'面试');assert.equal(applyCommand(s,{type:'import',data,overwrite:true}).revision,s.revision)});
test('quoted CSV and backup round trip',()=>{const data=parseCSV('公司,职位,岗位 JD,备注\n示例,工程师,负责产品开发,"包含,逗号\n和换行"');assert.equal(data.applications[0].jd,'负责产品开发');assert.equal(data.applications[0].notes,'包含,逗号\n和换行');let s=applyCommand(emptyState(),{type:'import',data});assert.deepEqual(normalizeImport(exportState(s)).applications,s.applications);assert.throws(()=>normalizeImport({version:99,events:[]}))});
test('SQLite mutations are atomic and reject stale revision',()=>{const db=openStore(':memory:');db.dispatch({type:'upsert',kind:'applications',record:job},0);assert.throws(()=>db.dispatch({type:'delete',kind:'applications',id:'a'},0),/其他窗口/);assert.equal(db.read().applications.length,1);assert.throws(()=>db.dispatch({type:'upsert',kind:'events',record:{title:'bad',date:'bad'}},1));assert.equal(db.read().revision,1);db.close()});
test('same batch duplicates do not create duplicate applications',()=>{const s=applyCommand(emptyState(),{type:'import',data:{applications:[{...job,id:'a'},{...job,id:'b'}]}});assert.equal(s.applications.length,1)});
test('backup import retains audit history',()=>{const s=applyCommand(emptyState(),{type:'upsert',kind:'applications',record:job});const restored=applyCommand(emptyState(),{type:'import',data:exportState(s)});assert.equal(restored.history[0].id,s.history[0].id)});
