import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';import {z} from 'zod';
import {openStore} from './db.mjs';import {previewImport,dateKey} from '../web/core/model.mjs';
const db=openStore(),server=new McpServer({name:'offer-island',version:'0.3.0'});
const result=x=>({content:[{type:'text',text:JSON.stringify(x)}]});
function tool(name,description,inputSchema,cb,readOnly=false){server.registerTool(name,{description,inputSchema,annotations:{readOnlyHint:readOnly,destructiveHint:false}},async args=>{try{return result(await cb(args))}catch(e){return {isError:true,content:[{type:'text',text:e.message}]}}})}
const revision={expectedRevision:z.number().int().nonnegative().describe('Revision returned by list_applications/list_today. Prevents overwriting concurrent changes.')};
tool('list_applications','Read applications, source evidence and current revision.',{query:z.string().optional()},({query=''})=>{const s=db.read();return {revision:s.revision,applications:s.applications.filter(a=>`${a.company} ${a.role}`.includes(query))}},true);
tool('upsert_application','Create or update a job application. Preserve source text, never infer dates. Updates require ID; use preview_import for deduplication.',{record:z.object({id:z.string().optional(),company:z.string().optional(),role:z.string().optional(),status:z.string().optional(),date:z.string().optional(),notes:z.string().optional(),next:z.string().optional(),link:z.string().optional(),source:z.string().optional(),rawStatus:z.string().optional()}),...revision},({record,expectedRevision})=>db.dispatch({type:'upsert',kind:'applications',record,actor:'agent'},expectedRevision));
tool('create_event','Create or update a dated event; date is required and must be explicitly confirmed. Use a stable ID for idempotent retries.',{record:z.object({id:z.string().optional(),title:z.string(),date:z.string(),time:z.string().optional(),type:z.string().optional(),job:z.string().optional(),location:z.string().optional(),notes:z.string().optional(),source:z.string().optional(),done:z.boolean().optional()}),...revision},({record,expectedRevision})=>db.dispatch({type:'upsert',kind:'events',record,actor:'agent'},expectedRevision));
tool('list_today','Read events for a local calendar date, defaults to today.',{date:z.string().optional()},({date=dateKey()})=>{const s=db.read();return {revision:s.revision,date,events:s.events.filter(e=>e.date===date).sort((a,b)=>a.time.localeCompare(b.time))}},true);
tool('preview_import','Validate screenshot/text extraction or backups and show additions, changes and duplicates without writing.',{data:z.record(z.unknown())},({data})=>{const s=db.read();return {revision:s.revision,changes:previewImport(s,data)}},true);
tool('commit_import','Apply a reviewed import. Default adds only; overwrite explicitly allows updates. All writes can be undone in the UI.',{data:z.record(z.unknown()),overwrite:z.boolean().default(false),...revision},({data,overwrite,expectedRevision})=>db.dispatch({type:'import',data,overwrite,actor:'agent'},expectedRevision));
tool('undo_last_change','Undo the most recent mutation, including Agent writes.',revision,({expectedRevision})=>db.dispatch({type:'undo',actor:'agent'},expectedRevision));
await server.connect(new StdioServerTransport());
